### ISSUE TITLE
Could you provide Baidu Cloud download links?

### ISSUE THREAD

**Issue by olojuwin** [saeed-anwar/DRLN#1]
I can't download from google drive。
It's really depressing！

**Comment by saeed-anwar** [comment]
I haven't found a simple way to make a baidu account.
:(

**Comment by olojuwin** [comment]
> I haven't found a simple way to make a baidu account.
> :(

Thanks,I've downloaded it from Google 。If you agre，I can provide links to Baidu Cloud。

**Comment by saeed-anwar** [comment]
You can send me the link, I will integrate it in the page.

**Comment by olojuwin** [comment]
> You can send me the link, I will integrate it in the page.

https://pan.baidu.com/s/1lAWlfQJHBJc3u9okpOL3lA

**Comment by saeed-anwar** [comment]
Thanks
