### ISSUE TITLE
How to garrantee every pixels of training images are being used?

### ISSUE THREAD

**Issue by nahidq** [saeed-anwar/DRLN#7]
Based on your code it seems patches randomly are cropped from the input image, unlike the previous approaches in which all patches from training images are extracting with overlapping or without overlap, then the net is trained with these patches.  But in your approach, RGB input patches are randomly cropped from training images. Then, it seems that not every pixel in training images is being processed in one epoch.  are there some reasons?  how we can make sure that we used all pixels of images also overlapping can has effects on the results.

**Comment by saeed-anwar** [comment]
Hi,

I think you mean to use every pixel of each training image in the training data. We don't need to use every pixel, we need enough data for the model to be trained on. 

If you want to use all the overlapping patches, then you can extract patches, save it and use accordingly.
